# Generated by Django 4.2.9 on 2025-11-14 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255, verbose_name='Legal Name')),
                ('trade_name', models.CharField(blank=True, max_length=255, verbose_name='Trade Name')),
                ('company_type', models.CharField(choices=[('llc', 'LLC (Limited Liability Company)'), ('s_corp', 'S-Corporation'), ('c_corp', 'C-Corporation'), ('partnership', 'Partnership'), ('sole_proprietorship', 'Sole Proprietorship'), ('other', 'Other')], max_length=30, verbose_name='Company Type')),
                ('ein', models.CharField(help_text='Employer Identification Number', max_length=20, unique=True, verbose_name='EIN')),
                ('address', models.TextField(verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('zip_code', models.CharField(max_length=20, verbose_name='ZIP Code')),
                ('country', models.CharField(default='USA', max_length=100, verbose_name='Country')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'hr_companies',
                'ordering': ['legal_name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'hr_departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=20, unique=True, verbose_name='Employee Number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('cpf', models.CharField(blank=True, help_text='Brazilian tax ID', max_length=14, verbose_name='CPF')),
                ('ssn', models.CharField(blank=True, help_text='Social Security Number (USA)', max_length=11, verbose_name='SSN')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG/ID')),
                ('marital_status', models.CharField(blank=True, max_length=20, verbose_name='Marital Status')),
                ('nationality', models.CharField(default='Brasileiro', max_length=50, verbose_name='Nationality')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='ZIP Code')),
                ('country', models.CharField(default='Brasil', max_length=100, verbose_name='Country')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, verbose_name='Emergency Contact Name')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Emergency Contact Phone')),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50, verbose_name='Emergency Contact Relation')),
                ('job_title', models.CharField(max_length=100, verbose_name='Job Title')),
                ('contract_type', models.CharField(choices=[('w2_employee', 'W2 Employee (Physical Person)'), ('1099_contractor', '1099 Contractor (Company)'), ('llc', 'LLC'), ('s_corp', 'S-Corp'), ('c_corp', 'C-Corp'), ('partnership', 'Partnership'), ('clt', 'CLT (Brazil)'), ('pj', 'PJ (Brazil)'), ('intern', 'Intern'), ('temporary', 'Temporary')], default='w2_employee', max_length=20, verbose_name='Contract Type')),
                ('hire_type', models.CharField(choices=[('individual', 'Physical Person'), ('company', 'Via Company')], default='individual', max_length=20, verbose_name='Hire Type')),
                ('hire_date', models.DateField(verbose_name='Hire Date')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='Termination Date')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Base Salary')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Commission (%)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('terminated', 'Terminated'), ('resigned', 'Resigned')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.ForeignKey(blank=True, help_text='Company of the person (if hired via company)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.company', verbose_name='Company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.department', verbose_name='Department')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='hr.employee', verbose_name='Supervisor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'hr_employees',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='hr.employee', verbose_name='Manager'),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(help_text='Physical person who owns this company', on_delete=django.db.models.deletion.CASCADE, related_name='owned_companies', to='hr.employee', verbose_name='Owner'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_number'], name='hr_employee_employe_024e37_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'status'], name='hr_employee_departm_e39e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['hire_type', 'company'], name='hr_employee_hire_ty_235f0f_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['ein'], name='hr_companie_ein_d7aecb_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['owner', 'is_active'], name='hr_companie_owner_i_279409_idx'),
        ),
    ]
