# Generated by Django 4.2.9 on 2025-11-14 18:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0002_benefit_vacation_training_timerecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('inss', 'INSS'), ('irrf', 'IRRF')], max_length=10, verbose_name='Tax Type')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('month', models.IntegerField(blank=True, help_text='Null for annual tables', null=True, verbose_name='Month')),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Min Value')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, help_text='Null for unlimited', max_digits=15, null=True, verbose_name='Max Value')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Rate (%)')),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Deduction')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Tax Table',
                'verbose_name_plural': 'Tax Tables',
                'db_table': 'hr_tax_tables',
                'ordering': ['tax_type', 'year', 'min_value'],
                'indexes': [models.Index(fields=['tax_type', 'year', 'is_active'], name='hr_tax_tabl_tax_typ_31b2f5_idx')],
                'unique_together': {('tax_type', 'year', 'month', 'min_value')},
            },
        ),
        migrations.CreateModel(
            name='HRNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('vacation_expiring', 'Vacation Expiring'), ('vacation_balance_low', 'Vacation Balance Low'), ('document_expiring', 'Document Expiring'), ('time_record_pending', 'Time Record Pending Approval'), ('vacation_request', 'Vacation Request'), ('payroll_processed', 'Payroll Processed'), ('other', 'Other')], max_length=30, verbose_name='Type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='Action URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hr.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'HR Notification',
                'verbose_name_plural': 'HR Notifications',
                'db_table': 'hr_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'is_read'], name='hr_notifica_employe_8bb315_idx'), models.Index(fields=['notification_type', 'created_at'], name='hr_notifica_notific_b3bf09_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('position', 'Position Change'), ('salary', 'Salary Change'), ('department', 'Department Change'), ('promotion', 'Promotion'), ('transfer', 'Transfer')], max_length=20, verbose_name='Change Type')),
                ('old_job_title', models.CharField(blank=True, max_length=100, verbose_name='Old Job Title')),
                ('old_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Old Salary')),
                ('new_job_title', models.CharField(blank=True, max_length=100, verbose_name='New Job Title')),
                ('new_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='New Salary')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('effective_date', models.DateField(verbose_name='Effective Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_history_changes', to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='hr.employee', verbose_name='Employee')),
                ('new_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_employee_history', to='hr.department', verbose_name='New Department')),
                ('old_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_employee_history', to='hr.department', verbose_name='Old Department')),
            ],
            options={
                'verbose_name': 'Employee History',
                'verbose_name_plural': 'Employee History',
                'db_table': 'hr_employee_history',
                'ordering': ['-effective_date', '-created_at'],
                'indexes': [models.Index(fields=['employee', 'change_type'], name='hr_employee_employe_a40976_idx'), models.Index(fields=['effective_date'], name='hr_employee_effecti_452b7c_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('work_permit', 'Work Permit'), ('id_card', 'ID Card'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('contract', 'Contract'), ('other', 'Other')], max_length=30, verbose_name='Document Type')),
                ('name', models.CharField(max_length=255, verbose_name='Document Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(upload_to='employee_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='File')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee Document',
                'verbose_name_plural': 'Employee Documents',
                'db_table': 'hr_employee_documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'document_type'], name='hr_employee_employe_f591c8_idx'), models.Index(fields=['expiry_date', 'is_active'], name='hr_employee_expiry__aeb124_idx')],
            },
        ),
    ]
