# Generated by Django 4.2.9 on 2025-11-14 18:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_employee_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_number'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AddField(
            model_name='employee',
            name='days_off',
            field=models.CharField(blank=True, help_text='e.g., Saturday, Sunday', max_length=50, verbose_name='Days Off'),
        ),
        migrations.AddField(
            model_name='employee',
            name='disability_description',
            field=models.TextField(blank=True, verbose_name='Disability Description'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ethnicity',
            field=models.CharField(blank=True, help_text='Optional, for compliance purposes', max_length=50, verbose_name='Ethnicity'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='employee',
            name='has_disability',
            field=models.BooleanField(default=False, help_text='Optional, for compliance purposes', verbose_name='Has Disability'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hr/employee_photos/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Probation End Date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_period_days',
            field=models.IntegerField(blank=True, default=90, null=True, verbose_name='Probation Period (days)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='weekly_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=40, max_digits=5, null=True, verbose_name='Weekly Hours'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_schedule_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Work Schedule End'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_schedule_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Work Schedule Start'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_shift',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night'), ('full_time', 'Full Time'), ('flexible', 'Flexible')], max_length=20, verbose_name='Work Shift'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, help_text='Legacy field, use job_position instead', max_length=100, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('common_law', 'Common Law Marriage')], max_length=20, verbose_name='Marital Status'),
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code (e.g., DEV-JR, SALES-MGR)', max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('level', models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior'), ('pleno', 'Mid-Level'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager'), ('director', 'Director'), ('vp', 'Vice President'), ('c_level', 'C-Level')], max_length=20, verbose_name='Level')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary for this position', max_digits=15, null=True, verbose_name='Minimum Salary')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary for this position', max_digits=15, null=True, verbose_name='Maximum Salary')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('requirements', models.TextField(blank=True, verbose_name='Requirements')),
                ('responsibilities', models.TextField(blank=True, verbose_name='Responsibilities')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to='hr.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Job Position',
                'verbose_name_plural': 'Job Positions',
                'db_table': 'hr_job_positions',
                'ordering': ['department', 'level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('elementary', 'Elementary School'), ('middle', 'Middle School'), ('high_school', 'High School'), ('technical', 'Technical Course'), ('bachelor', "Bachelor's Degree"), ('specialization', 'Specialization'), ('masters', "Master's Degree"), ('phd', 'PhD'), ('post_phd', 'Post-Doctorate')], max_length=30, verbose_name='Level')),
                ('institution', models.CharField(max_length=255, verbose_name='Institution')),
                ('course', models.CharField(blank=True, max_length=255, verbose_name='Course')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_completed', models.BooleanField(default=True, verbose_name='Completed')),
                ('graduation_year', models.IntegerField(blank=True, null=True, verbose_name='Graduation Year')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='hr/education_certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Certificate File')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='hr.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'db_table': 'hr_educations',
                'ordering': ['-end_date', '-graduation_year', 'level'],
            },
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('ssn', models.CharField(blank=True, max_length=11, verbose_name='SSN')),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('son', 'Son'), ('daughter', 'Daughter'), ('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('other', 'Other')], max_length=20, verbose_name='Relationship')),
                ('is_tax_dependent', models.BooleanField(default=True, verbose_name='Tax Dependent')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='hr.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Dependent',
                'verbose_name_plural': 'Dependents',
                'db_table': 'hr_dependents',
                'ordering': ['employee', 'relationship', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('w2_employee', 'W2 Employee Contract'), ('1099_contractor', '1099 Contractor Agreement'), ('clt', 'CLT Contract (Brazil)'), ('pj', 'PJ Contract (Brazil)'), ('llc', 'LLC Service Agreement'), ('s_corp', 'S-Corp Service Agreement'), ('c_corp', 'C-Corp Service Agreement'), ('partnership', 'Partnership Agreement'), ('intern', 'Internship Agreement'), ('temporary', 'Temporary Work Agreement')], max_length=30, verbose_name='Contract Type')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Contract Number')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for indefinite contracts', null=True, verbose_name='End Date')),
                ('signature_date', models.DateField(blank=True, null=True, verbose_name='Signature Date')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='hr/contracts/%Y/%m/', verbose_name='PDF File')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_signature', 'Pending Signature'), ('signed', 'Signed'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='draft', max_length=30, verbose_name='Status')),
                ('contract_data', models.JSONField(blank=True, default=dict, help_text='Additional contract data in JSON format', verbose_name='Contract Data')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Generated at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='hr.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'db_table': 'hr_contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('bank_code', models.CharField(blank=True, max_length=20, verbose_name='Bank Code')),
                ('agency', models.CharField(max_length=20, verbose_name='Agency')),
                ('account_number', models.CharField(max_length=50, verbose_name='Account Number')),
                ('account_type', models.CharField(choices=[('checking', 'Checking Account'), ('savings', 'Savings Account')], default='checking', max_length=20, verbose_name='Account Type')),
                ('pix_key', models.CharField(blank=True, help_text='PIX key (Brazil) or payment key', max_length=255, verbose_name='PIX Key')),
                ('pix_key_type', models.CharField(blank=True, choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('email', 'Email'), ('phone', 'Phone'), ('random', 'Random Key')], max_length=20, verbose_name='PIX Key Type')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Account')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='hr.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'db_table': 'hr_bank_accounts',
                'ordering': ['-is_primary', 'bank_name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.jobposition', verbose_name='Job Position'),
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('job_title', models.CharField(max_length=200, verbose_name='Job Title')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_current', models.BooleanField(default=False, verbose_name='Current Job')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('responsibilities', models.TextField(blank=True, verbose_name='Responsibilities')),
                ('achievements', models.TextField(blank=True, verbose_name='Achievements')),
                ('reference_name', models.CharField(blank=True, max_length=255, verbose_name='Reference Name')),
                ('reference_phone', models.CharField(blank=True, max_length=20, verbose_name='Reference Phone')),
                ('reference_email', models.EmailField(blank=True, max_length=254, verbose_name='Reference Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='hr.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
                'db_table': 'hr_work_experiences',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['employee'], name='hr_work_exp_employe_42083e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='jobposition',
            index=models.Index(fields=['code'], name='hr_job_posi_code_07af99_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposition',
            index=models.Index(fields=['department', 'is_active'], name='hr_job_posi_departm_6ba543_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposition',
            index=models.Index(fields=['level', 'is_active'], name='hr_job_posi_level_afcfb6_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['employee'], name='hr_educatio_employe_340f22_idx'),
        ),
        migrations.AddIndex(
            model_name='dependent',
            index=models.Index(fields=['employee', 'is_active'], name='hr_dependen_employe_f713a9_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['employee', 'status'], name='hr_contract_employe_04df0b_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_type', 'status'], name='hr_contract_contrac_63e505_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_number'], name='hr_contract_contrac_7981d8_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['employee', 'is_active'], name='hr_bank_acc_employe_9d1621_idx'),
        ),
    ]
