# Generated by Django 4.2.9 on 2025-11-15 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('quickbooks', 'QuickBooks Online'), ('xero', 'Xero'), ('stripe', 'Stripe'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('zapier', 'Zapier'), ('plaid', 'Plaid'), ('twilio', 'Twilio'), ('sendgrid', 'SendGrid'), ('hubspot', 'HubSpot'), ('salesforce', 'Salesforce'), ('custom', 'Custom Integration')], max_length=50, verbose_name='Integration Type')),
                ('name', models.CharField(help_text='Custom name for this integration instance', max_length=200, verbose_name='Integration Name')),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('error', 'Error'), ('expired', 'Expired')], default='inactive', max_length=20, verbose_name='Status')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Integration-specific configuration', verbose_name='Configuration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='Last Error')),
                ('error_count', models.IntegerField(default=0, verbose_name='Error Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integration',
                'verbose_name_plural': 'Integrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickBooksIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text='OAuth 2.0 access token', verbose_name='Access Token')),
                ('refresh_token', models.TextField(help_text='OAuth 2.0 refresh token', verbose_name='Refresh Token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Token Expires At')),
                ('realm_id', models.CharField(help_text='QuickBooks company ID', max_length=100, verbose_name='Realm ID')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Company Name')),
                ('company_id', models.CharField(blank=True, max_length=100, verbose_name='Company ID')),
                ('sync_customers', models.BooleanField(default=True, verbose_name='Sync Customers')),
                ('sync_invoices', models.BooleanField(default=True, verbose_name='Sync Invoices')),
                ('sync_payments', models.BooleanField(default=True, verbose_name='Sync Payments')),
                ('sync_items', models.BooleanField(default=True, verbose_name='Sync Items')),
                ('sync_employees', models.BooleanField(default=False, verbose_name='Sync Employees')),
                ('sync_direction', models.CharField(choices=[('innexar_to_qb', 'Innexar → QuickBooks'), ('qb_to_innexar', 'QuickBooks → Innexar'), ('bidirectional', 'Bidirectional')], default='bidirectional', max_length=20, verbose_name='Sync Direction')),
                ('auto_sync_enabled', models.BooleanField(default=False, verbose_name='Auto Sync Enabled')),
                ('sync_interval_minutes', models.IntegerField(default=60, verbose_name='Sync Interval (minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quickbooks', to='integrations.integration', verbose_name='Integration')),
            ],
            options={
                'verbose_name': 'QuickBooks Integration',
                'verbose_name_plural': 'QuickBooks Integrations',
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('sync', 'Sync'), ('auth', 'Authentication'), ('error', 'Error'), ('webhook', 'Webhook'), ('manual', 'Manual Action')], max_length=20, verbose_name='Log Type')),
                ('message', models.TextField(verbose_name='Message')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details')),
                ('success', models.BooleanField(default=True, verbose_name='Success')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integrations.integration', verbose_name='Integration')),
            ],
            options={
                'verbose_name': 'Integration Log',
                'verbose_name_plural': 'Integration Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['integration_type', 'is_active'], name='integration_integra_2a24b6_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['integration', 'log_type', 'created_at'], name='integration_integra_965c4c_idx'),
        ),
    ]
