# Generated by Django 4.2.9 on 2025-11-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('legal_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Legal Name')),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID')),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Registration Number')),
                ('country', models.CharField(choices=[('BR', 'Brazil'), ('US', 'United States'), ('ES', 'Spain'), ('MX', 'Mexico'), ('AR', 'Argentina'), ('CO', 'Colombia'), ('CL', 'Chile'), ('PE', 'Peru'), ('PT', 'Portugal'), ('CA', 'Canada'), ('GB', 'United Kingdom'), ('DE', 'Germany'), ('FR', 'France'), ('IT', 'Italy'), ('AU', 'Australia')], default='BR', max_length=2, verbose_name='Country')),
                ('currency', models.CharField(choices=[('BRL', 'R$ - Brazilian Real'), ('USD', '$ - US Dollar'), ('EUR', '€ - Euro'), ('MXN', '$ - Mexican Peso'), ('ARS', '$ - Argentine Peso'), ('COP', '$ - Colombian Peso'), ('CLP', '$ - Chilean Peso'), ('PEN', 'S/ - Peruvian Sol'), ('GBP', '£ - British Pound'), ('CAD', '$ - Canadian Dollar'), ('AUD', '$ - Australian Dollar')], default='BRL', max_length=3, verbose_name='Currency')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=50, verbose_name='Timezone')),
                ('language', models.CharField(choices=[('pt', 'Portuguese'), ('en', 'English'), ('es', 'Spanish')], default='pt', max_length=5, verbose_name='Language')),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', max_length=20, verbose_name='Date Format')),
                ('time_format', models.CharField(choices=[('24h', '24 hours'), ('12h', '12 hours (AM/PM)')], default='24h', max_length=10, verbose_name='Time Format')),
                ('business_type', models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('manufacturing', 'Manufacturing'), ('services', 'Services'), ('ecommerce', 'E-commerce'), ('restaurant', 'Restaurant/Food Service'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('construction', 'Construction'), ('logistics', 'Logistics/Transportation'), ('technology', 'Technology/IT'), ('consulting', 'Consulting'), ('other', 'Other')], max_length=50, verbose_name='Business Type')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='Industry')),
                ('main_activity', models.CharField(choices=[('products', 'Products'), ('services', 'Services'), ('both', 'Products and Services')], default='products', max_length=50, verbose_name='Main Activity')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State/Province')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('fiscal_year_start', models.CharField(choices=[('01-01', 'January 1st'), ('04-01', 'April 1st'), ('07-01', 'July 1st'), ('10-01', 'October 1st')], default='01-01', max_length=5, verbose_name='Fiscal Year Start')),
                ('tax_regime', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax Regime')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant Settings',
                'verbose_name_plural': 'Tenant Settings',
                'db_table': 'tenants_settings',
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
