# Generated by Django 4.2.9 on 2025-11-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantsettings_tenant_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='legal_entity_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual/Person'), ('llc', 'LLC - Limited Liability Company'), ('corporation', 'Corporation'), ('partnership', 'Partnership'), ('sole_proprietorship', 'Sole Proprietorship'), ('nonprofit', 'Non-Profit Organization'), ('other', 'Other')], max_length=50, null=True, verbose_name='Legal Entity Type'),
        ),
    ]
